### ISSUE TITLE
Dart 2 typing issue

### ISSUE THREAD

**Issue by DrivEddy** [lejard-h/flutter_google_places_autocomplete#8]
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'List' is not a subtype of type 'List<String>' in type cast where
  List is from dart:core
  List is from dart:core
  String is from dart:core

#0      Object._as (dart:core/runtime/libobject_patch.dart)
#1      new Prediction.fromJson (package:google_maps_webservice/src/places.dart:621:25)
#2      PlacesAutocompleteResponse._predictions (package:google_maps_webservice/src/places.dart:572:27)
#3      new PlacesAutocompleteResponse.fromJson (package:google_maps_webservice/src/places.dart:580:11)
#4      GoogleMapsPlaces._decodeAutocompleteResponse (package:google_maps_webservice/src/places.dart:263:11)
#5      GoogleMapsPlaces.autocomplete (package:google_maps_webservice/src/places.dart:115:12)
<asynchronous suspension>
```

**Comment by DrivEddy** [comment]
Ok is on https://github.com/lejard-h/google_maps_webservice/issues
